### ISSUE TITLE
confusing information about the provider authentication

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-fortios#28]
I was reading the documenation

https://www.terraform.io/docs/providers/fortios/index.html

and it's not clear what the referred 'token' argument is and where I can set it up in the router? Is it the password of a user?

Can you provide more information about that topic?

Greetings and thanks,
Tobias

**Comment by frankshen01** [comment]
Hi @tkoeck  sorry that you are running into trouble while configuring the token. I will introduce the token configuration for you.

**Token introduction:**
The FortiOS token-based authentication is done via a single FortiOS API token. This token is only generated once when creating an API admin. The user must store this token in a safe place because it cannot be retrieved again. The Terraform Provider for FortiOS will include the token in order to be authenticated as the associated API admin.

**Configuration:**
You can configure the token through CLI:
```
mytestFortiGate (testapiuser) # show
config system api-user
    edit "testapiuser"
        set accprofile "super_admin"
        set vdom "root"
        config trusthost
            edit 1
                set ipv4-trusthost 192.168.0.0 255.255.0.0
            next
        end
    next
end

mytestFortiGate (testapiuser) # end
mytestFortiGate # execute api-user generate-key testapiuser 
New API key: wgtNn3Qng7Q0ywpwmx3dt4fhtHs3d5
```
The API key here is the token. Or you can configure it with GUI too: System->Administrators->Create New: REST API Admin.

**Additional:**
You can learn more about api-user from:
https://docs.fortinet.com/document/fortigate/6.0.6/cli-reference/883891/system-api-user
https://docs.fortinet.com/document/fortigate/6.0.6/cli-reference/474886/api-user

You can refer to page 10,11 of FortiOS - REST API Reference for more instructions for token
https://fndn.fortinet.net/index.php?/documents/file/149-fortios-60-rest-api-reference-603/

I hope this will help. Thank you!

**Comment by tkoeck** [comment]
Looks great. We will look into it. You should provide this additional information in the Terraform provider documenation so that others can follow it as well.
