### ISSUE TITLE
changing admin_sport to 8443 will halt 'terraform apply'

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-fortios#29]
I was playing around with the fortios provider. If I wanted to change the

_resource "fortios_system_setting_global" "fglobal" {
  admintimeout = 240
  hostname = "hh"
  timezone = "33"
  admin_sport = 8443
  admin_ssh_port = 22
}_

to the new admin_sport a terraform apply will stall the application forever.

A usage of TF_LOG has been shown that it is obviously not possible to change the port because it will still try to use the Port 443 for api usage.

_fortios_system_setting_dns.dns: Still creating... [30s elapsed]
2019-08-06T16:17:38.177+0200 [DEBUG] plugin.terraform-provider-fortios_v1.1.0_x4: 2019/08/06 16:17:38 Error found: Put https://hh.someurl.de/api/v2/cmdb/system/dns?vdom=root&access_token=SOMETOKEN: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), will resend again https://hh.someurl.de/api/v2/cmdb/system/dns?vdom=root&access_token=sometoken, 2_

That works forever until I break it up with Ctrl-C.

After I setup the router port manually back to 443 it worked again.

**Comment by frankshen01** [comment]
Hi, @tkoeck  since the FortiOS Provider needs to communicate with the firewall through admin_sport , so after modifying the port number, we have to restart terraform. There are two solutions to solve this:

**Option I**
1 Configure the Firewall's admin_sport to 8443 manually.
2 Set the Provider part of the configuration file, add the 8443 port number to the hostname and separate them with a colon, as follows: 
```
provider "fortios" {
        hostname= "YourIP:8443"
        token = "nx6nbGn8tnFddaa3Qy79jpjfsyw1"
        insecure = "true"
}
```

**Option II**
1 Set the admin_sport port in the terraform configuration file as follows:
```
provider "fortios" {
        hostname= "YourIP"
        token = "nx6nbGn8tnFddaa3Qy79jpjfsyw1"
        insecure = "true"
}

resource "fortios_system_setting_global" "fglobal" {
        admintimeout = 240
        hostname = "hh"
        timezone = "33"
        admin_sport = 8443
        admin_ssh_port = 22
}
```
Then execute "terraform init; terraform plan; terraform apply". After a few seconds or more (depending on your network situation), then press Ctrl+C to end the apply command. If your network is okay, the admin_sport will be successfully set to 8443.

2 Set the Provider part of the configuration file, add the 8443 port number to the hostname and separate them with a colon, as follows, then re-apply terraform: 
```
provider "fortios" {
        hostname= "YourIP:8443"
        token = "nx6nbGn8tnFddaa3Qy79jpjfsyw1"
        insecure = "true"
}

# ...
```
This should solve your problem. 

We will add an example and description for the custom port in the documentation too. Thank you!
