### ISSUE TITLE
Release related

### ISSUE THREAD

**Issue by 4ndersonLin** [terraform-providers/terraform-provider-fortios#55]
Does there is any release policy or schedule here? we want to know this and evaluate to use terraform to management our Fortigate or not.

**Comment by hpernicha** [comment]
Hi @4ndersonLin 

We have plans and procedures in place to maintain and extend the support we have for FortiManager and FortiOS in Terraform. Unfortunately we can't discuss it's contents or timeframes in here.
But feel free to reach out to us if there is any specific function you need. Also, because you have a FortiManager, you can also try to use our FNDN site for more resources related to devops, FortiManager FortiOS and the integration with Terraform.

Thanks
Hugo Pernicha, Product Manager at Fortinet

**Comment by 4ndersonLin** [comment]
@hpernicha Great to know this and thanks for your advice. We will try to use the FNDN site first and do some tests on our dev environment.

Best,
Anderson Lin
